Controllers/CardController.cs
using BussinessLayer.Repos;
using BussinessLayer.ViewModels;
using DataAccess;
using DataAccess.Model;
using Microsoft.AspNetCore.Mvc;
using Services_Layer.Services;
using Stripe;
using System.Security.Claims;

namespace Presentaion.Controllers
{
    public class CardController : Controller
    {
        private readonly ShopingCartRepo _cartRepo;
        private readonly IConfiguration _configuration;

        public CardController(ShopingCartRepo cartRepo,IConfiguration configuration)
        {
            this._cartRepo = cartRepo;
            this._configuration = configuration;
        }

        public async Task<IActionResult> AddToCard(string id, int Quantity = 1)
        {
            if (User.Identity.IsAuthenticated)
            {
                var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
                await _cartRepo.AddToCard(userid, id, Quantity);

                return RedirectToAction("ShowAll", "Product");
            }
            return RedirectToAction("LogIn", "Account");
        }
        public async Task<IActionResult> Profile()
        {
            if (User.Identity.IsAuthenticated)
            {
                var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var vm = await _cartRepo.GetCardInfoAsync(userid);


                return View(vm);
            }
            return RedirectToAction("LogIn", "Account");
        }
        public async Task<IActionResult> Remove(string id)
        {
            var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _cartRepo.RemoveFromCard(userid, id);
            return RedirectToAction("Profile");
        }

    
        


    }
}

Views/Shared/_CreateItem.cshtml
@model string;

@if (User.IsInRole("Admin"))

{
    <div style="position: fixed; left: 25px; top: 25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Add" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Presentaion</title>
    <title>Stylish - Shoes Online Store</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="author" content="TemplatesJungle">
    <meta name="keywords" content="Online Store">
    <meta name="description" content="Stylish - Shoes Online Store HTML Template">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="~/css/vendor.css">
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=Playfair+Display:ital,wght@0,900;1,900&family=Source+Sans+Pro:wght@400;600;700;900&display=swap"
          rel="stylesheet">
</head>
<body>
    <partial name="_SymbolsSectionPatialView" />
    <header id="header" class="site-header text-black">

        <nav id="header-nav" class="navbar navbar-expand-lg">
            <div class="container-lg">
                <a class="navbar-brand" asp-action="Index" asp-controller="Home">
                    <img src="images/main-logo.png" class="logo" alt="logo">
                </a>
                <button class="navbar-toggler d-flex d-lg-none order-3 border-0 p-1 ms-2" type="button" data-bs-toggle="offcanvas"
                        data-bs-target="#bdNavbar" aria-controls="bdNavbar" aria-expanded="false" aria-label="Toggle navigation">
                    <svg class="navbar-icon">
                        <use xlink:href="#navbar-icon"></use>
                    </svg>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="bdNavbar">
                    <div class="offcanvas-header px-4 pb-0">
                        <a class="navbar-brand ps-3" href="index.html">
                            <img src="images/main-logo.png" class="logo" alt="logo">
                        </a>
                        <button type="button" class="btn-close btn-close-black p-5" data-bs-dismiss="offcanvas" aria-label="Close"
                                data-bs-target="#bdNavbar"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul id="navbar" class="navbar-nav fw-bold justify-content-end align-items-center flex-grow-1">
                            <li class="nav-item ">
                                <a class="nav-link me-5" asp-action="Index" asp-controller="Home">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link me-5" href="#">Men</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link me-5" href="#">Women</a>
                            </li>
                            @*                             <li class="nav-item dropdown">
                            <a class="nav-link me-5 active dropdown-toggle border-0" href="#" data-bs-toggle="dropdown"
                            aria-expanded="false">Page</a>
                            <ul class="dropdown-menu fw-bold">
                            <li>
                            <a href="index.html" class="dropdown-item">About Us </a>
                            </li>
                            <li>
                            <a class="dropdown-item" href="index.html">Shop </a>
                            </li>
                            <li>
                            <a class="dropdown-item" href="index.html">Blog </a>
                            </li>
                            <li>
                            <a class="dropdown-item" href="index.html">Single Product </a>
                            </li>
                            <li>
                            <a class="dropdown-item" href="index.html">Single Post </a>
                            </li>
                            <li>
                            <a class="dropdown-item" href="index.html">Styles </a>
                            </li>
                            <li>
                            <a href="#" data-bs-toggle="modal" data-bs-target="#modallong" class="dropdown-item">cart</a>
                            </li>
                            <li>
                            <a href="#" data-bs-toggle="modal" data-bs-target="#modallogin" class="dropdown-item">Login</a>
                            </li>
                            </ul>
                            </li>
                            *@
                            <li class="nav-item">
                                <a class="nav-link me-5" asp-action="ShowAll" asp-controller="Product">Shop</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link me-5" href="#">Sale</a>
                            </li>
                            @if (User.Identity.IsAuthenticated)
                            {

                                <li class="nav-item">
                                    <a class="nav-link me-5" asp-action="logout" asp-controller="Account">Log Out</a>
                                </li>
                                <li class="nav-item d-flex justify-content-between align-items-center">
                                    <a class="nav-link me-5" asp-action="Profile" asp-controller="Card">Welcome  <span>@User.Identity.Name</span> </a>
                                </li>

                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link me-5" asp-action="LogIn" asp-controller="Account">Log In</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
                @*                 <div class="user-items ps-0 ps-md-5">
                <ul class="d-flex justify-content-end list-unstyled align-item-center m-0">
                <li class="pe-3">
                <a asp-action="LogIn" asp-controller="Account" data-bs-toggle="modal" data-bs-target="#modallogin" class="border-0">
                <svg class="user" width="24" height="24">
                <use xlink:href="#user"></use>
                </svg>
                </a>
                </li>
                <li class="pe-3">
                <a asp-action="ShopingCart" asp-controller="User" data-bs-toggle="modal" data-bs-target="#modallong" class="border-0">
                <svg class="shopping-cart" width="24" height="24">
                <use xlink:href="#shopping-cart"></use>
                </svg>
                </a>
                </li>
                <li>
                <a asp-action="search" asp-controller="Product" class="search-item border-0" data-bs-toggle="collapse" data-bs-target="#search-box" aria-label="Toggle navigation">
                <svg class="search" width="24" height="24">
                <use xlink:href="#search"></use>
                </svg>
                </a>
                </li>
                </ul>
                </div>
                *@
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer id="footer" class="py-5 border-top">
        <div class="container-lg">
            <div class="row">
                <div class="col-lg-2 pb-3">
                    <div class="footer-menu">
                        <h5 class="widget-title pb-2">Info</h5>
                        <ul class="menu-list list-unstyled">
                            <li class="pb-2">
                                <a href="#">Track Your Order</a>
                            </li>
                            <li class="pb-2">
                                <a href="index.html">Our Blog</a>
                            </li>
                            <li class="pb-2">
                                <a href="#">Privacy policy</a>
                            </li>
                            <li class="pb-2">
                                <a href="#">Shipping</a>
                            </li>
                            <li class="pb-2">
                                <a href="#">Contact Us</a>
                            </li>
                            <li class="pb-2">
                                <a href="#">Help</a>
                            </li>
                            <li class="pb-2">
                                <a href="#">Community</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 pb-3">
                    <div class="footer-menu">
                        <h5 class="widget-title pb-2">About</h5>
                        <ul class="menu-list list-unstyled">
                            <li class="pb-2">
                                <a href="#">History</a>
                            </li>
                            <li class="pb-2">
                                <a href="#">Our Team</a>
                            </li>
                            <li class="pb-2">
                                <a href="#">Services</a>
                            </li>
                            <li class="pb-2">
                                <a href="#">Company</a>
                            </li>
                            <li class="pb-2">
                                <a href="#">Manufacture</a>
                            </li>
                            <li class="pb-2">
                                <a href="#">Wholesale</a>
                            </li>
                            <li class="pb-2">
                                <a href="#">Retail</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 pb-3">
                    <div class="footer-menu">
                        <h5 class="widget-title pb-2">Women Shoes</h5>
                        <ul class="menu-list list-unstyled">

                            <li class="pb-2">
                                <a href="index.html">Our Blog</a>
                            </li>

                            <li class="pb-2">
                                <a href="#">Shipping</a>
                            </li>

                            <li class="pb-2">
                                <a href="#">Help</a>
                            </li>

                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 pb-3">
                    <div class="footer-menu">
                        <h5 class="widget-title pb-2">Popular</h5>
                        <ul class="menu-list list-unstyled">
                            <li class="pb-2">
                                <a href="#">Prices Drop</a>
                            </li>
                            <li class="pb-2">
                                <a href="#">New Products</a>
                            </li>
                            <li class="pb-2">
                                <a href="#">Best Sales</a>
                            </li>
                            <li class="pb-2">
                                <a href="index.html">Stores</a>
                            </li>
                            <li class="pb-2">
                                <a asp-action="LogIn" asp-controller="Account" data-bs-toggle="modal" data-bs-target="#modallogin">Login</a>
                            </li>
                            <li class="pb-2">
                                <a asp-action="ShopingCart" asp-controller="User" data-bs-toggle="modal" data-bs-target="#modallong">Cart</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-2 pb-3">
                    <div class="footer-menu">
                        <h5 class="widget-title pb-3">Get In Touch</h5>
                        <div class="footer-contact-text">

                            <span> Call us: (+02) 010 6303 8833 </span>
                            <span class="text-hover fw-bold light-border">
                                <a href="ahm75295@gmail.com">Contact </a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="js/jquery-1.11.0.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="js/plugins.js"></script>
    <script src="js/script.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_SymbolsSectionPatialView.cshtml
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol xmlns="http://www.w3.org/2000/svg" id="shopping-carriage" viewBox="0 0 24 24" fill="none">
        <path d="M5 22H19C20.103 22 21 21.103 21 20V9C21 8.73478 20.8946 8.48043 20.7071 8.29289C20.5196 8.10536 20.2652 8 20 8H17V7C17 4.243 14.757 2 12 2C9.243 2 7 4.243 7 7V8H4C3.73478 8 3.48043 8.10536 3.29289 8.29289C3.10536 8.48043 3 8.73478 3 9V20C3 21.103 3.897 22 5 22ZM9 7C9 5.346 10.346 4 12 4C13.654 4 15 5.346 15 7V8H9V7ZM5 10H7V12H9V10H15V12H17V10H19L19.002 20H5V10Z"
              fill="black" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="quick-view" viewBox="0 0 24 24">
        <path fill="currentColor"
              d="M10 18a7.952 7.952 0 0 0 4.897-1.688l4.396 4.396l1.414-1.414l-4.396-4.396A7.952 7.952 0 0 0 18 10c0-4.411-3.589-8-8-8s-8 3.589-8 8s3.589 8 8 8zm0-14c3.309 0 6 2.691 6 6s-2.691 6-6 6s-6-2.691-6-6s2.691-6 6-6z" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="shopping-cart" viewBox="0 0 24 24" fill="none">
        <path d="M21 4H2V6H4.3L7.582 15.025C7.79362 15.6029 8.1773 16.1021 8.68134 16.4552C9.18539 16.8083 9.78556 16.9985 10.401 17H19V15H10.401C9.982 15 9.604 14.735 9.461 14.342L8.973 13H18.246C19.136 13 19.926 12.402 20.169 11.549L21.962 5.275C22.0039 5.12615 22.0109 4.96962 21.9823 4.81763C21.9537 4.66565 21.8904 4.52234 21.7973 4.39889C21.7041 4.27544 21.5837 4.1752 21.4454 4.106C21.3071 4.0368 21.1546 4.00053 21 4ZM18.246 11H8.246L6.428 6H19.675L18.246 11Z"
              fill="black" />
        <path d="M10.5 21C11.3284 21 12 20.3284 12 19.5C12 18.6716 11.3284 18 10.5 18C9.67157 18 9 18.6716 9 19.5C9 20.3284 9.67157 21 10.5 21Z"
              fill="black" />
        <path d="M16.5 21C17.3284 21 18 20.3284 18 19.5C18 18.6716 17.3284 18 16.5 18C15.6716 18 15 18.6716 15 19.5C15 20.3284 15.6716 21 16.5 21Z"
              fill="black" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="nav-icon" viewBox="0 0 16 16">
        <path d="M14 10.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-7a.5.5 0 0 0 0 1h7a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0 0 1h11a.5.5 0 0 0 .5-.5z" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="close" viewBox="0 0 16 16">
        <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="navbar-icon" viewBox="0 0 16 16">
        <path d="M14 10.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-7a.5.5 0 0 0 0 1h7a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0 0 1h11a.5.5 0 0 0 .5-.5z" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="plus" viewBox="0 0 24 24">
        <path fill="currentColor" d="M19 12.998h-6v6h-2v-6H5v-2h6v-6h2v6h6z" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="minus" viewBox="0 0 24 24">
        <path fill="currentColor" d="M19 12.998H5v-2h14z" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="dropdown" viewBox="0 0 24 24">
        <path fill="currentColor" d="m7 10l5 5l5-5H7Z" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="user" viewBox="0 0 24 24">
        <path fill="currentColor"
              d="M12 2a5 5 0 1 0 5 5a5 5 0 0 0-5-5zm0 8a3 3 0 1 1 3-3a3 3 0 0 1-3 3zm9 11v-1a7 7 0 0 0-7-7h-4a7 7 0 0 0-7 7v1h2v-1a5 5 0 0 1 5-5h4a5 5 0 0 1 5 5v1z" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="arrow-right" viewBox="0 0 24 24">
        <path fill="currentColor"
              d="M13.3 17.275q-.3-.3-.288-.725t.313-.725L16.15 13H5q-.425 0-.713-.288T4 12q0-.425.288-.713T5 11h11.15L13.3 8.15q-.3-.3-.3-.713t.3-.712q.3-.3.713-.3t.712.3L19.3 11.3q.15.15.213.325t.062.375q0 .2-.063.375t-.212.325l-4.6 4.6q-.275.275-.687.275t-.713-.3Z" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="facebook" viewBox="0 0 24 24">
        <path fill="currentColor"
              d="M9.198 21.5h4v-8.01h3.604l.396-3.98h-4V7.5a1 1 0 0 1 1-1h3v-4h-3a5 5 0 0 0-5 5v2.01h-2l-.396 3.98h2.396v8.01Z" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="twitter" viewBox="0 0 512 512">
        <path fill="currentColor"
              d="M496 109.5a201.8 201.8 0 0 1-56.55 15.3a97.51 97.51 0 0 0 43.33-53.6a197.74 197.74 0 0 1-62.56 23.5A99.14 99.14 0 0 0 348.31 64c-54.42 0-98.46 43.4-98.46 96.9a93.21 93.21 0 0 0 2.54 22.1a280.7 280.7 0 0 1-203-101.3A95.69 95.69 0 0 0 36 130.4c0 33.6 17.53 63.3 44 80.7A97.5 97.5 0 0 1 35.22 199v1.2c0 47 34 86.1 79 95a100.76 100.76 0 0 1-25.94 3.4a94.38 94.38 0 0 1-18.51-1.8c12.51 38.5 48.92 66.5 92.05 67.3A199.59 199.59 0 0 1 39.5 405.6a203 203 0 0 1-23.5-1.4A278.68 278.68 0 0 0 166.74 448c181.36 0 280.44-147.7 280.44-275.8c0-4.2-.11-8.4-.31-12.5A198.48 198.48 0 0 0 496 109.5Z" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="youtube" viewBox="0 0 32 32">
        <path fill="currentColor"
              d="M29.41 9.26a3.5 3.5 0 0 0-2.47-2.47C24.76 6.2 16 6.2 16 6.2s-8.76 0-10.94.59a3.5 3.5 0 0 0-2.47 2.47A36.13 36.13 0 0 0 2 16a36.13 36.13 0 0 0 .59 6.74a3.5 3.5 0 0 0 2.47 2.47c2.18.59 10.94.59 10.94.59s8.76 0 10.94-.59a3.5 3.5 0 0 0 2.47-2.47A36.13 36.13 0 0 0 30 16a36.13 36.13 0 0 0-.59-6.74ZM13.2 20.2v-8.4l7.27 4.2Z" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="instagram" viewBox="0 0 256 256">
        <path fill="currentColor"
              d="M128 80a48 48 0 1 0 48 48a48.05 48.05 0 0 0-48-48Zm0 80a32 32 0 1 1 32-32a32 32 0 0 1-32 32Zm48-136H80a56.06 56.06 0 0 0-56 56v96a56.06 56.06 0 0 0 56 56h96a56.06 56.06 0 0 0 56-56V80a56.06 56.06 0 0 0-56-56Zm40 152a40 40 0 0 1-40 40H80a40 40 0 0 1-40-40V80a40 40 0 0 1 40-40h96a40 40 0 0 1 40 40ZM192 76a12 12 0 1 1-12-12a12 12 0 0 1 12 12Z" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="pinterest" viewBox="0 0 24 24">
        <path fill="currentColor"
              d="M9.04 21.54c.96.29 1.93.46 2.96.46a10 10 0 0 0 10-10A10 10 0 0 0 12 2A10 10 0 0 0 2 12c0 4.25 2.67 7.9 6.44 9.34c-.09-.78-.18-2.07 0-2.96l1.15-4.94s-.29-.58-.29-1.5c0-1.38.86-2.41 1.84-2.41c.86 0 1.26.63 1.26 1.44c0 .86-.57 2.09-.86 3.27c-.17.98.52 1.84 1.52 1.84c1.78 0 3.16-1.9 3.16-4.58c0-2.4-1.72-4.04-4.19-4.04c-2.82 0-4.48 2.1-4.48 4.31c0 .86.28 1.73.74 2.3c.09.06.09.14.06.29l-.29 1.09c0 .17-.11.23-.28.11c-1.28-.56-2.02-2.38-2.02-3.85c0-3.16 2.24-6.03 6.56-6.03c3.44 0 6.12 2.47 6.12 5.75c0 3.44-2.13 6.2-5.18 6.2c-.97 0-1.92-.52-2.26-1.13l-.67 2.37c-.23.86-.86 2.01-1.29 2.7v-.03Z" />
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" id="search" viewBox="0 0 24 24">
        <path fill="currentColor"
              d="M10 18a7.952 7.952 0 0 0 4.897-1.688l4.396 4.396l1.414-1.414l-4.396-4.396A7.952 7.952 0 0 0 18 10c0-4.411-3.589-8-8-8s-8 3.589-8 8s3.589 8 8 8zm0-14c3.309 0 6 2.691 6 6s-2.691 6-6 6s-6-2.691-6-6s2.691-6 6-6z" />
    </symbol>
</svg>